<a href='https://www.darshan.ac.in/'> <img src='https://www.darshan.ac.in/Content/media/DU_Logo.svg' width="150" height="200"/></a>
<pre>
<center><b><h2> Python for Data Science - 2305CS303 </b></center>
<center><b><h2>Lab - 8</b></center>    
<left><b><h3>Roll No. : 106</b></left>  
<left><b><h3>Name : Ghorecha Harsh</b></left>   
<pre>    

### 1. import numpy library.

In [2]:
import numpy as np

### 2.Create an array of 10 zeros

In [10]:
arr = np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


### 3. Create an array of 10 ones.


In [12]:
arr = np.ones(10)
print(arr)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


### 4. Create an array of 10 fives

In [22]:
arr = np.ones(10)*5
print(arr)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


### 5. Create an array of integers from 10 to 50.

In [28]:
arr1 = np.arange(10,51)
print(arr1)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


### 6. Create an array of all the even integers from 10 to 50.

In [30]:
arr2 = np.arange(10,51,2)
print(arr2)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


### 7. Create a 3x3 matrix with values ranging from 0 to 8.

In [46]:
arr3 = np.arange(9).reshape(3,3)
print(arr3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


### 8. Create a 3x3 identity matrix.

In [40]:
arr4 = np.diag([1,1,1])
arr4

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

### 9. Use Numpy to generate a random number between 0 and 1


In [50]:
arr5 = np.random.rand()
arr5

0.23562477690924943

### 10. Use Numpy to generate an array of 25 random numbers sampled from a standard normal distribution.

In [80]:
arr6 = np.random.randint(1,26,25)
arr6

array([21,  9,  7, 24, 18, 13, 21, 16,  5,  6,  5, 11, 18, 10, 13, 16,  6,
       12, 13, 19, 20, 19, 17,  1,  6])

### 11. Create linspace array

In [92]:
arr6 = np.linspace(1,25,5)
arr6

array([ 1.,  7., 13., 19., 25.])

### 12. Create an array of 20 linearly spaced points between 0 and 1. 

In [102]:
arr7 = np.linspace(0,1)
print(arr7)

[0.         0.02040816 0.04081633 0.06122449 0.08163265 0.10204082
 0.12244898 0.14285714 0.16326531 0.18367347 0.20408163 0.2244898
 0.24489796 0.26530612 0.28571429 0.30612245 0.32653061 0.34693878
 0.36734694 0.3877551  0.40816327 0.42857143 0.44897959 0.46938776
 0.48979592 0.51020408 0.53061224 0.55102041 0.57142857 0.59183673
 0.6122449  0.63265306 0.65306122 0.67346939 0.69387755 0.71428571
 0.73469388 0.75510204 0.7755102  0.79591837 0.81632653 0.83673469
 0.85714286 0.87755102 0.89795918 0.91836735 0.93877551 0.95918367
 0.97959184 1.        ]


### 13. Create Random Integer Array

In [94]:
arr6 = np.random.randint(1,26,25)
arr6

array([13, 21,  1,  1, 11, 15, 10, 18, 17,  5,  7, 12, 16, 19, 14, 11, 24,
       11, 17,  4, 16, 24, 16, 21,  4])

### 14. Create Random Integer Array and Reshape that Array

In [98]:
arr6 = np.random.randint(1,24,24).reshape(6,4)
arr6

array([[ 4, 16,  2, 11],
       [21, 15,  7, 19],
       [ 3,  1,  5, 21],
       [23,  1,  5, 10],
       [21, 11, 19, 19],
       [ 2, 22, 14,  9]])